export const FIND_ALL_TODOS_START = 'FIND_ALL_TODOS_START'
export const FIND_ALL_TODOS_END = 'FIND_ALL_TODOS_END'

export const TOGGLE_TODO_START = 'TOGGLE_TODO_START'
export const TOGGLE_TODO_END = 'TOGGLE_TODO_END'